//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.42000
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabreTools.Helper.Resources {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SabreTools.Helper.Resources.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This is the default help output.
		/// </summary>
		public static string Default_Desc {
			get {
				return ResourceManager.GetString("Default_Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Remove and restore rom headers.
		/// </summary>
		public static string Headerer_Desc {
			get {
				return ResourceManager.GetString("Headerer_Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Headerer.
		/// </summary>
		public static string Headerer_Name {
			get {
				return ResourceManager.GetString("Headerer_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to C# port of the Romba rom management tool.
		/// </summary>
		public static string RombaSharp_Desc {
			get {
				return ResourceManager.GetString("RombaSharp_Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to RombaSharp.
		/// </summary>
		public static string RombaSharp_Name {
			get {
				return ResourceManager.GetString("RombaSharp_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Import, generate, manipulate DAT files.
		/// </summary>
		public static string SabreTools_Desc {
			get {
				return ResourceManager.GetString("SabreTools_Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SabreTools.
		/// </summary>
		public static string SabreTools_Name {
			get {
				return ResourceManager.GetString("SabreTools_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Basic rebuild using a DAT.
		/// </summary>
		public static string SimpleSort_Desc {
			get {
				return ResourceManager.GetString("SimpleSort_Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SimpleSort.
		/// </summary>
		public static string SimpleSort_Name {
			get {
				return ResourceManager.GetString("SimpleSort_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Convert files to TGZ output.
		/// </summary>
		public static string TGZTest_Desc {
			get {
				return ResourceManager.GetString("TGZTest_Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to TGZConvert.
		/// </summary>
		public static string TGZTest_Name {
			get {
				return ResourceManager.GetString("TGZTest_Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Usage.
		/// </summary>
		public static string Usage {
			get {
				return ResourceManager.GetString("Usage", resourceCulture);
			}
		}
	}
}
