using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DATabase
{
	class Remapping
	{
		public static Dictionary<string, string> MAME;
		public static Dictionary<string, string> NoIntro;
		public static Dictionary<string, string> Redump;
		public static Dictionary<string, string> TOSEC;
		public static Dictionary<string, string> TruRip;

		public static void CreateRemappings()
		{
			MAME = new Dictionary<string, string>();

			MAME.Add("32x.xml", "Sega - 32X");
			MAME.Add("3do_m2.xml", "Panasonic - 3DO M2");
			MAME.Add("a2600.xml", "Atari - 2600");
			MAME.Add("a2600_cass.xml", "Atari - 2600");
			MAME.Add("a5200.xml", "Atari - 5200");
			MAME.Add("a7800.xml", "Atari - 7800");
			MAME.Add("a800.xml", "Atari - 8bit");
			MAME.Add("a800_flop.xml", "Atari - 8bit");
			MAME.Add("abc1600.xml", "Luxor - ABC 1600");
			MAME.Add("abc800.xml", "Luxor - ABC 800");
			MAME.Add("abc800_hdd.xml", "Luxor - ABC 800");
			MAME.Add("abc806.xml", "Luxor - ABC 806");
			MAME.Add("abc80_cass.xml", "Luxor - ABC 80");
			MAME.Add("abc80_flop.xml", "Luxor - ABC 80");
			MAME.Add("adam_cart.xml", "Coleco - ColecoVision, ColecoVision ADAM");
			MAME.Add("adam_cass.xml", "Coleco - ColecoVision, ColecoVision ADAM");
			MAME.Add("adam_flop.xml", "Coleco - ColecoVision, ColecoVision ADAM");
			MAME.Add("advantage.xml", "NorthStar - Advantage");
			MAME.Add("advision.xml", "Entex - Adventure Vision");
			MAME.Add("aim65_cart.xml", "Rockwell - AIM 65");
			MAME.Add("aleste.xml", "Patisonic - Aleste 520EX");
			MAME.Add("alice32.xml", "Matra Hachette - Alice 32 & 90");
			MAME.Add("alice90.xml", "Matra Hachette - Alice 32 & 90");
			MAME.Add("alphatro_flop.xml", "Triumph-Adler - Alphatronic PC");
			MAME.Add("altos5.xml", "Altos Computer Systems - Series 5");
			MAME.Add("amiga_a1000.xml", "Commodore - Amiga");
			MAME.Add("amiga_a3000.xml", "Commodore - Amiga");
			MAME.Add("amiga_apps.xml", "Commodore - Amiga");
			MAME.Add("amiga_flop.xml", "Commodore - Amiga");
			MAME.Add("amiga_hardware.xml", "Commodore - Amiga");
			MAME.Add("amiga_workbench.xml", "Commodore - Amiga");
			MAME.Add("amigaaga_flop.xml", "Commodore - Amiga");
			MAME.Add("amigaecs_flop.xml", "Commodore - Amiga");
			MAME.Add("amigaocs_flop.xml", "Commodore - Amiga");
			MAME.Add("ampro.xml", "Ampro - Little Board");
			MAME.Add("apc.xml", "NEC - Advanced Personal Computer");
			MAME.Add("apfimag_cass.xml", "APF - M-1000");
			MAME.Add("apfm1000.xml", "APF - M-1000");
			MAME.Add("apogee.xml", "Radio-86RK - Apogej BK-01");
			MAME.Add("apollo_ctape.xml", "Hewlett-Packard - Apollo");
			MAME.Add("apple1.xml", "Apple - I");
			MAME.Add("apple2.xml", "Apple - II");
			MAME.Add("apple2gs.xml", "Apple  - II");
			MAME.Add("apple3.xml", "Apple - III");
			MAME.Add("aquarius.xml", "Mattel - Aquarius");
			MAME.Add("arcadia.xml", "Emerson - Arcadia 2001");
			MAME.Add("archimedes.xml", "Acorn - Archimedes");
			MAME.Add("astrocde.xml", "Bally Professional - Arcade, Astrocade");
			MAME.Add("atom.xml", "Acorn - Atom");
			MAME.Add("atom_cass.xml", "Acorn - Atom");
			MAME.Add("atom_flop.xml", "Acorn - Atom");
			MAME.Add("atom_rom.xml", "Acorn - Atom");
			MAME.Add("attache.xml", "Otrona - Attache");
			MAME.Add("b2m.xml", "BNPO - Bashkiria-2M");
			MAME.Add("bbc_32016_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_65c102_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_68000_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_80186_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_arm_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_flop_32016.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_flop_6502.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_flop_65c102.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_flop_68000.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_flop_80186.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_flop_arm.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_flop_torch.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_flop_z80.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_torch_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbc_z80_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbca_cass.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcb_cass.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcb_cass_de.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcb_de_cass.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcb_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcb_flop_orig.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcb_flop_us.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcb_orig_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcb_us_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcbc.xml", "BBC - Bridge Companion");
			MAME.Add("bbcm_cart.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcm_cass.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcm_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bbcmc_flop.xml", "Acorn - BBC, Electron");
			MAME.Add("bk0010.xml", "Elektronika - BK-0010");
			MAME.Add("bml3_flop.xml", "Hitachi - Basic Master Level 3");
			MAME.Add("bw12.xml", "Bondwell - 12");
			MAME.Add("bw14.xml", "Bondwell - 14");
			MAME.Add("bw2.xml", "Bondwell - 2");
			MAME.Add("bx256hp_flop.xml", "Commodore - BX256-80HP, CBM 730");
			MAME.Add("c128_cart.xml", "Commodore - 128");
			MAME.Add("c128_flop.xml", "Commodore - 128");
			MAME.Add("c128_rom.xml", "Commodore - 128");
			MAME.Add("c64_cart.xml", "Commodore - 64");
			MAME.Add("c64_cass.xml", "Commodore - 64");
			MAME.Add("c64_flop.xml", "Commodore - 64");
			MAME.Add("c65_flop.xml", "Commodore - 65");
			MAME.Add("casloopy.xml", "Casio - Loopy");
			MAME.Add("cbm2_cart.xml", "Commodore - CBM-II");
			MAME.Add("cbm2_flop.xml", "Commodore - CBM-II");
			MAME.Add("cbm8096_flop.xml", "Commodore - 8096");
			MAME.Add("cbm8296_flop.xml", "Commodore - 8296");
			MAME.Add("cc40_cart.xml", "Texas Instruments - CC-40");
			MAME.Add("cd32.xml", "Commodore - Amiga");
			MAME.Add("cdi.xml", "Philips - CD-i");
			MAME.Add("cdtv.xml", "Commodore - Amiga");
			MAME.Add("cgenie_cart.xml", "EACA - EG2000 Colour Genie");
			MAME.Add("cgenie_cass.xml", "EACA - EG2000 Colour Genie");
			MAME.Add("channelf.xml", "Fairchild - Channel F");
			MAME.Add("coco_cart.xml", "Tandy Radio Shack - TRS-80 Color Computer");
			MAME.Add("coco_flop.xml", "Tandy Radio Shack - TRS-80 Color Computer");
			MAME.Add("coleco.xml", "Coleco - ColecoVision, ColecoVision ADAM");
			MAME.Add("compclr2_flop.xml", "ISC - Compucolor II");
			MAME.Add("compis.xml", "Telenova - Compis");
			MAME.Add("comx35_flop.xml", "COMX - COMX-35");
			MAME.Add("copera.xml", "Sega - PICO");
			MAME.Add("cpc_cass.xml", "Amstrad - CPC");
			MAME.Add("cpc_flop.xml", "Amstrad - CPC");
			MAME.Add("crvision.xml", "VTech - CreatiVision");
			MAME.Add("cx3000tc.xml", "Palson - CX 3000 Tele Computer");
			MAME.Add("dai_cass.xml", "DAI - Personal Computer");
			MAME.Add("database.xml", "Voltmace - Database");
			MAME.Add("dim68k.xml", "Dimension - 68000");
			MAME.Add("dmv.xml", "NCR - Decision Mate V");
			MAME.Add("dps1.xml", "Ithaca InterSystems - DPS-1");
			MAME.Add("ec1841.xml", "MPO BT - EC 1841");
			MAME.Add("einstein.xml", "Tatung - Einstein TC-01");
			MAME.Add("electron_cart.xml", "Acorn - BBC, Electron");
			MAME.Add("ep64_cart.xml", "Enterprise - 64");
			MAME.Add("ep64_cass.xml", "Enterprise - 64");
			MAME.Add("ep64_flop.xml", "Enterprise - 64");
			MAME.Add("epson_cpm.xml", "Epson - CPM");
			MAME.Add("exl100.xml", "Exelvision Exeltel, EXL100");
			MAME.Add("famicom_cass.xml", "Nintendo - Famicom BASIC");
			MAME.Add("famicom_flop.xml", "Nintendo - Famicom Disk System");
			MAME.Add("fm77av.xml", "Fujitsu - FM-77AV");
			MAME.Add("fm7_cass.xml", "Fujitsu - FM-7");
			MAME.Add("fm7_disk.xml", "Fujitsu - FM-7");
			MAME.Add("fmtowns_cd.xml", "Fujitsu - FM Towns");
			MAME.Add("g7400.xml", "Philips - Videopac+, Odyssey2");
			MAME.Add("galaxy.xml", "Galaksija  - Galaksija, Galaksija Plus");
			MAME.Add("gamate.xml", "Bit Corp - Gamate");
			MAME.Add("gameboy.xml", "Nintendo - Game Boy");
			MAME.Add("gamecom.xml", "Tiger - Game.com");
			MAME.Add("gamegear.xml", "Sega - Game Gear");
			MAME.Add("gameking.xml", "TimeTop - GameKing");
			MAME.Add("gameking3.xml", "TimeTop - GameKing");
			MAME.Add("gamepock.xml", "Epoch - Game Pocket Computer");
			MAME.Add("gba.xml", "Nintendo - Game Boy Advance");
			MAME.Add("gbcolor.xml", "Nintendo - Game Boy Color");
			MAME.Add("genius.xml", "VTech - Genius");
			MAME.Add("gimix.xml", "Gimix - 6809");
			MAME.Add("gjmovie.xml", "VTech - Genius");
			MAME.Add("gl2000.xml", "VTech - Genius");
			MAME.Add("gl6000sl.xml", "VTech - Genius");
			MAME.Add("glcolor.xml", "VTech - Genius");
			MAME.Add("gmaster.xml", "Hartung - Game Master");
			MAME.Add("gp32.xml", "GamePark - GP32");
			MAME.Add("guab.xml", "JPM - Give us a Break");
			MAME.Add("gx4000.xml", "Amstrad - GX4000");
			MAME.Add("h21.xml", "TRQ - Video Computer H-21");
			MAME.Add("horizon.xml", "NorthStar - Horizon");
			MAME.Add("hp9835a_rom.xml", "Hewlett-Packard - 9835");
			MAME.Add("hp9845a_rom.xml", "Hewlett-Packard - 9845");
			MAME.Add("hp9845b_rom.xml", "Hewlett-Packard - 9845");
			MAME.Add("ht68k.xml", "Hawthorne Technologies - HT68K");
			MAME.Add("i7000_card.xml", "Itautec - I-7000");
			MAME.Add("ibm5140.xml", "IBM - PC Compatibles");
			MAME.Add("ibm5150.xml", "IBM - PC Compatibles");
			MAME.Add("ibm5150_cass.xml", "IBM - PC Compatibles");
			MAME.Add("ibm5160_flop.xml", "IBM - PC Compatibles");
			MAME.Add("ibm5170.xml", "IBM - PC Compatibles");
			MAME.Add("ibm5170_cdrom.xml", "IBM - PC Compatibles");
			MAME.Add("ibmpcjr_cart.xml", "IBM - PC Jr");
			MAME.Add("ibmpcjr_flop.xml", "IBM - PC Jr");
			MAME.Add("interact.xml", "Interact - Family Computer");
			MAME.Add("intv.xml", "Mattel - Intellivision");
			MAME.Add("intvecs.xml", "Mattel - Intellivision");
			MAME.Add("iq128.xml", "VTech - Genius");
			MAME.Add("iq151_cart.xml", "ZPA Novy Bor - IQ-151");
			MAME.Add("iq151_flop.xml", "ZPA Novy Bor - IQ-151");
			MAME.Add("jaguar.xml", "Atari - Jaguar");
			MAME.Add("juicebox.xml", "Mattel - Juice Box");
			MAME.Add("jupace_cass.xml", "Jupiter Cantab - Jupiter Ace");
			MAME.Add("kayproii.xml", "Kaypro - II");
			MAME.Add("kc_cart.xml", "Robotron - KC85");
			MAME.Add("kc_cass.xml", "Robotron - KC85");
			MAME.Add("kc_flop.xml", "Robotron - KC85");
			MAME.Add("korvet_flop.xml", "Moscow State University - Korvet");
			MAME.Add("lantutor.xml", "Texas Instruments - Language Tutor");
			MAME.Add("leapster.xml", "LeapFrog - Leapster Learning Game System");
			MAME.Add("lisa.xml", "Apple - Lisa");
			MAME.Add("lisa2.xml", "Apple - Lisa 2");
			MAME.Add("lviv.xml", "Lviv  - PC-01");
			MAME.Add("lynx.xml", "Atari - Lynx");
			MAME.Add("m20.xml", "Olivetti - M20");
			MAME.Add("m5_cart.xml", "Sord - M5");
			MAME.Add("m5_cass.xml", "Sord - M5");
			MAME.Add("mac_flop.xml", "Apple - Macintosh");
			MAME.Add("mac_hdd.xml", "Apple - Macintosh");
			MAME.Add("mbc200.xml", "Sanyo - MBC-200, MBC-1200");
			MAME.Add("mbc55x.xml", "Sanyo - MBC-550, MBC-555");
			MAME.Add("mc10.xml", "Tandy Radio Shack - TRS-80 MC-10");
			MAME.Add("mc1000_cass.xml", "CCE - MC-1000");
			MAME.Add("mc1502_flop.xml", "Elektronika - MC 1502");
			MAME.Add("md2_flop.xml", "Morrow - Micro Decision MD-2");
			MAME.Add("megacd.xml", "Sega - Mega-CD, Sega CD");
			MAME.Add("megacdj.xml", "Sega - Mega-CD, Sega CD");
			MAME.Add("megadriv.xml", "Sega - Mega Drive, Genesis");
			MAME.Add("megaduck.xml", "Creatronic - Mega Duck, Cougar Boy");
			MAME.Add("megapc.xml", "Amstrad - Mega PC");
			MAME.Add("megatech.xml", "Sega - Megatech");
			MAME.Add("microvision.xml", "Milton Bradley - MicroVision");
			MAME.Add("mikro80.xml", "Radio-86RK - Mikro-80");
			MAME.Add("mikrosha_cart.xml", "Radio-86RK - Mikrosha");
			MAME.Add("mikrosha_cass.xml", "Radio-86RK - Mikrosha");
			MAME.Add("misterx.xml", "Yeno - MisterX");
			MAME.Add("mm1_flop.xml", "Nokia - MikroMikko 1");
			MAME.Add("mo5_cart.xml", "Thomson - 8bit");
			MAME.Add("mpu1000.xml", "Acetronic - MPU-1000");
			MAME.Add("mpz80.xml", "Morrow - MPZ80");
			MAME.Add("msx1_cart.xml", "Microsoft - MSX, MSX 2");
			MAME.Add("msx1_cass.xml", "Microsoft - MSX, MSX 2");
			MAME.Add("msx1_flop.xml", "Microsoft - MSX, MSX 2");
			MAME.Add("msx2_cart.xml", "Microsoft - MSX, MSX 2");
			MAME.Add("msx2_cass.xml", "Microsoft - MSX, MSX 2");
			MAME.Add("msx2_flop.xml", "Microsoft - MSX, MSX 2");
			MAME.Add("msx2p_flop.xml", "Microsoft - MSX, MSX 2");
			MAME.Add("msxr_flop.xml", "Microsoft - MSX, MSX 2");
			MAME.Add("mtx_cass.xml", "Memotech - MTX512");
			MAME.Add("myvision.xml", "Nichibutsu - My Vision");
			MAME.Add("mz2000_cass.xml", "Sharp - MZ-2000");
			MAME.Add("mz2000_flop.xml", "Sharp - MZ-2000");
			MAME.Add("mz2500.xml", "Sharp - MZ-2500");
			MAME.Add("mz700_cass.xml", "Sharp - MZ-700");
			MAME.Add("mz800_cass.xml", "Sharp - MZ-800, M-1500");
			MAME.Add("n64.xml", "Nintendo - Nintendo 64");
			MAME.Add("n64dd.xml", "Nintendo - Nintendo 64DD");
			MAME.Add("nascom_flop.xml", "Nascom - I, II");
			MAME.Add("nascom_socket.xml", "Nascom - I, II");
			MAME.Add("neocd.xml", "SNK - Neo Geo CD");
			MAME.Add("neogeo.xml", "SNK - Neo-Geo");
			MAME.Add("nes.xml", "Nintendo - Nintendo Entertainment System");
			MAME.Add("nes_ade.xml", "Nintendo - Nintendo Entertainment System");
			MAME.Add("nes_datach.xml", "Nintendo - Nintendo Entertainment System");
			MAME.Add("nes_kstudio.xml", "Nintendo - Nintendo Entertainment System");
			MAME.Add("nes_ntbrom.xml", "Nintendo - Nintendo Entertainment System");
			MAME.Add("next.xml", "NeXT - NeXT");
			MAME.Add("ngp.xml", "SNK - Neo Geo Pocket");
			MAME.Add("ngpc.xml", "SNK - Neo Geo Pocket Color");
			MAME.Add("nimbus.xml", "RM - Nimbus PC");
			MAME.Add("odyssey2.xml", "Philips - Videopac+, Odyssey2");
			MAME.Add("ondra.xml", "Tesla - Ondra, Ondra ViLi");
			MAME.Add("orao.xml", "PEL Varazdin - Orao");
			MAME.Add("orion_cart.xml", "Orion - Orion 128, OrionPro");
			MAME.Add("orion_cass.xml", "Orion - Orion 128, OrionPro");
			MAME.Add("orion_flop.xml", "Orion - Orion 128, OrionPro");
			MAME.Add("orionpro_flop.xml", "Orion - Orion 128, OrionPro");
			MAME.Add("osborne1.xml", "OCC - Osborne 1, 2, 3, 4");
			MAME.Add("osborne2.xml", "OCC - Osborne 1, 2, 3, 4");
			MAME.Add("p500_flop.xml", "Commodore - P500");
			MAME.Add("partner_cass.xml", "Radio-86RK - Partner-01.01");
			MAME.Add("partner_flop.xml", "Radio-86RK - Partner-01.01");
			MAME.Add("pasogo.xml", "Koei - PasoGo");
			MAME.Add("pb2000c.xml", "Casio - PB-2000C");
			MAME.Add("pc1000.xml", "VTech - PreComputer 1000");
			MAME.Add("pc1512.xml", "Amstrad - PC1512");
			MAME.Add("pc1640.xml", "Amstrad - PC1640");
			MAME.Add("pc8201.xml", "NEC - PC-8201");
			MAME.Add("pc8801_cass.xml", "NEC - PC-8801");
			MAME.Add("pc8801_flop.xml", "NEC - PC-8801");
			MAME.Add("pc88va.xml", "NEC - PC-88VA");
			MAME.Add("pc98.xml", "NEC - PC-9801");
			MAME.Add("pce.xml", "NEC - PC Engine, TurboGrafx 16");
			MAME.Add("pcecd.xml", "NEC - PC Engine CD, TurboGrafx 16 CD");
			MAME.Add("pcw.xml", "Amstrad - PCW");
			MAME.Add("pcw16.xml", "Amstrad - PCW");
			MAME.Add("pecom_cass.xml", "Elektronska Industrija Nis - PECOM 32, 64");
			MAME.Add("pegasus_cart.xml", "Technosys - Aamber Pegasus");
			MAME.Add("pencil2.xml", "Hanimex - Pencil II");
			MAME.Add("pentagon_cass.xml", "Pentagon - 1024SL");
			MAME.Add("pet_cass.xml", "Commodore - PET");
			MAME.Add("pet_flop.xml", "Commodore - PET");
			MAME.Add("pet_hdd.xml", "Commodore - PET");
			MAME.Add("pet_rom.xml", "Commodore - PET");
			MAME.Add("pico.xml", "Sega - PICO");
			MAME.Add("pippin.xml", "Bandai - Pippin");
			MAME.Add("pippin_flop.xml", "Bandai - Pippin");
			MAME.Add("plus4_cart.xml", "Commodore - Plus-4");
			MAME.Add("plus4_cass.xml", "Commodore - Plus-4");
			MAME.Add("plus4_flop.xml", "Commodore - Plus-4");
			MAME.Add("pmd85_cass.xml", "Tesla - PMD 85");
			MAME.Add("pokemini.xml", "Nintendo - Pokemon Mini");
			MAME.Add("pro128_cart.xml", "Olivetti - Prodest PC 128");
			MAME.Add("pro128s_flop.xml", "Olivetti - Prodest PC 128");
			MAME.Add("prof180.xml", "Conitec - PROF-180");
			MAME.Add("prof80.xml", "Conitec - PROF-80");
			MAME.Add("psion1.xml", "Psion - Organiser I");
			MAME.Add("psion2.xml", "Psion - Organiser II");
			MAME.Add("psx.xml", "Sony - PlayStation");
			MAME.Add("pt68k2.xml", "Peripheral Technology - PT68K");
			MAME.Add("pv1000.xml", "Casio - PV-1000");
			MAME.Add("pv2000.xml", "Casio - PV-2000");
			MAME.Add("px4_cart.xml", "Epson - PX-4");
			MAME.Add("pyl601.xml", "SASDF - Pyldin-601");
			MAME.Add("ql_cart.xml", "Sinclair - QL");
			MAME.Add("ql_cass.xml", "Sinclair - QL");
			MAME.Add("ql_flop.xml", "Sinclair - QL");
			MAME.Add("qx10_flop.xml", "Epson - QX-10");
			MAME.Add("r9751.xml", "ROLM - CBX 9751");
			MAME.Add("radio86_cart.xml", "Radio-86RK - Radio-86RK");
			MAME.Add("radio86_cass.xml", "Radio-86RK - Radio-86RK");
			MAME.Add("rainbow.xml", "DEC - Rainbow 100");
			MAME.Add("rwtrntcs.xml", "Rowtron - Television Computer System");
			MAME.Add("rx78.xml", "Gundam - RX-78");
			MAME.Add("sage2.xml", "Sage - Sage II");
			MAME.Add("samcoupe_cass.xml", "MGT - Sam Coupe");
			MAME.Add("samcoupe_flop.xml", "MGT - Sam Coupe");
			MAME.Add("sat_cart.xml", "Sega - Saturn");
			MAME.Add("saturn.xml", "Sega - Saturn");
			MAME.Add("sawatte.xml", "Sega - PICO");
			MAME.Add("sc3000_cart.xml", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			MAME.Add("sc3000_cass.xml", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			MAME.Add("scv.xml", "Epoch - Super Cassette Vision");
			MAME.Add("segacd.xml", "Sega - Mega-CD, Sega CD");
			MAME.Add("sf7000.xml", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			MAME.Add("sg1000.xml", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			MAME.Add("sgx.xml", "NEC - Super Grafx");
			MAME.Add("smc777.xml", "Sony - SMC777");
			MAME.Add("sms.xml", "Sega - Master System, Mark III");
			MAME.Add("snes.xml", "Nintendo  - Super Nintendo Entertainment System");
			MAME.Add("snes_bspack.xml", "Nintendo  - Super Nintendo Entertainment System");
			MAME.Add("snes_strom.xml", "Nintendo  - Super Nintendo Entertainment System");
			MAME.Add("snes_vkun.xml", "Nintendo  - Super Nintendo Entertainment System");
			MAME.Add("snotec.xml", "Bandai - Super Note Club");
			MAME.Add("snread.xml", "Texas Instruments - Speak & Read");
			MAME.Add("snspell.xml", "Texas Instruments - Speak & Spell");
			MAME.Add("socrates.xml", "VTech - Socrates");
			MAME.Add("softbox.xml", "SSE - SoftBox");
			MAME.Add("sol20_cass.xml", "PTC - Sol Terminal Computer SOL-20");
			MAME.Add("sorcerer_cart.xml", "Exidy - Sorcerer");
			MAME.Add("sorcerer_cass.xml", "Exidy - Sorcerer");
			MAME.Add("sorcerer_flop.xml", "Exidy - Sorcerer");
			MAME.Add("spc1000_cass.xml", "Samsung - SPC-1000");
			MAME.Add("special_cass.xml", "Specialist - Specialist");
			MAME.Add("special_flop.xml", "Specialist - Specialist");
			MAME.Add("specpls3_flop.xml", "Sinclair - ZX Spectrum");
			MAME.Add("spectrum_cart.xml", "Sinclair - ZX Spectrum");
			MAME.Add("spectrum_cass.xml", "Sinclair - ZX Spectrum");
			MAME.Add("st_cart.xml", "Atari - ST");
			MAME.Add("st_flop.xml", "Atari - ST");
			MAME.Add("studio2.xml", "RCA - Studio II");
			MAME.Add("stv.xml", "Sega - Titan Video");
			MAME.Add("super6.xml", "ADC - Super Six");
			MAME.Add("superpet_flop.xml", "Commodore - SuperPET, MMF 9000");
			MAME.Add("supracan.xml", "Funtech - Super Acan");
			MAME.Add("sv8000.xml", "Bandai - Super Vision 8000");
			MAME.Add("svi318_cart.xml", "Spectravideo - SVI-318, SVI-328");
			MAME.Add("svi318_cass.xml", "Spectravideo - SVI-318, SVI-328");
			MAME.Add("svi318_flop.xml", "Spectravideo - SVI-318, SVI-328");
			MAME.Add("svision.xml", "Watara - Supervision");
			MAME.Add("svmu.xml", "Sega - Visual Memory System");
			MAME.Add("tandy200.xml", "Tandy Radio Shack - Model 200");
			MAME.Add("tandy2k.xml", "Tandy Radio Shack - 2000");
			MAME.Add("tandy6k.xml", "Tandy Radio Shack - 6000");
			MAME.Add("tdv2324.xml", "Tandberg - TDV 2324");
			MAME.Add("tek4052_cart.xml", "Tektronix - 4052");
			MAME.Add("tg16.xml", "NEC - PC Engine, TurboGrafx 16");
			MAME.Add("ti74_cart.xml", "Texas Instruments - TI-74");
			MAME.Add("ti99_cart.xml", "Texas Instruments - TI-99 4A");
			MAME.Add("tiki100.xml", "Tiki Data - Kontiki-100, Tiki-100");
			MAME.Add("timex_dock.xml", "Timex - TS-2068");
			MAME.Add("tntell.xml", "Texas Instruments - Touch & Tell");
			MAME.Add("to770_cart.xml", "Thomson - 8bit");
			MAME.Add("to7_cart.xml", "Thomson - 8bit");
			MAME.Add("trs80m2.xml", "Tandy Radio Shack - TRS-80 Model II");
			MAME.Add("trsm100.xml", "Tandy Radio Shack - TRS-80 Model 100");
			MAME.Add("tutor.xml", "Tomy - Tutor, Pyuuta");
			MAME.Add("tvc_cart.xml", "Videoton - TV-Computer");
			MAME.Add("tvc_cass.xml", "Videoton - TV-Computer");
			MAME.Add("tvc_flop.xml", "Videoton - TV-Computer");
			MAME.Add("unichamp.xml", "Unisonic - Champion 2711");
			MAME.Add("ut88.xml", "Radio-86RK - YuT-88");
			MAME.Add("uzebox.xml", "Uzebox - Uzebox");
			MAME.Add("v1050_flop.xml", "Visual Technology - Visual 1050");
			MAME.Add("v1050_hdd.xml", "Visual Technology - Visual 1050");
			MAME.Add("vboy.xml", "Nintendo - Virtual Boy");
			MAME.Add("vc4000.xml", "Interton - VC 4000");
			MAME.Add("vector06_cart.xml", "Temirazov & Sokolov - Vector-06C");
			MAME.Add("vectrex.xml", "GCE - Vectrex");
			MAME.Add("vg5k.xml", "Philips - VG-5000");
			MAME.Add("vic10.xml", "Commodore - VIC-10");
			MAME.Add("vic1001_cart.xml", "Commodore - VIC-20");
			MAME.Add("vic1001_cass.xml", "Commodore - VIC-20");
			MAME.Add("vic1001_flop.xml", "Commodore - VIC-20");
			MAME.Add("victor9k_flop.xml", "Sirius - Victor 9000");
			MAME.Add("vidbrain.xml", "VideoBrain - Family Computer");
			MAME.Add("vii.xml", "Chintendo - Vii");
			MAME.Add("vip.xml", "RCA - Vip");
			MAME.Add("visicom.xml", "Toshiba - Visicom");
			MAME.Add("vixen.xml", "OCC - Osborne 1, 2, 3, 4");
			MAME.Add("vreader.xml", "VTech - V.Reader, Storio");
			MAME.Add("vsmile_cart.xml", "VTech - V.Smile, V.Disc");
			MAME.Add("vsmile_cd.xml", "VTech - V.Smile, V.Disc");
			MAME.Add("vz_cass.xml", "Dick Smith Electronics - VZ-200, VZ-300");
			MAME.Add("wangpc.xml", "Wang - PC");
			MAME.Add("wicat.xml", "Millennium Systems - Wicat");
			MAME.Add("wmbullet.xml", "WaveMate - Bullet");
			MAME.Add("wscolor.xml", "Bandai - WonderSwan Color");
			MAME.Add("wswan.xml", "Bandai - WonderSwan");
			MAME.Add("x07_card.xml", "Canon - X-07");
			MAME.Add("x07_cass.xml", "Canon - X-07");
			MAME.Add("x1_cass.xml", "Sharp - X1");
			MAME.Add("x1_flop.xml", "Sharp - X1");
			MAME.Add("x68k_flop.xml", "Sharp - X68000");
			MAME.Add("xegs.xml", "Atari - 8bit");
			MAME.Add("xerox820.xml", "Xerox - 820");
			MAME.Add("xerox820ii.xml", "Xerox - 820 II");

			NoIntro = new Dictionary<string, string>();

			NoIntro.Add("Atari - 5200", "Atari - 5200");
			NoIntro.Add("Atari - 7800", "Atari - 7800");
			NoIntro.Add("Atari - Jaguar", "Atari - Jaguar");
			NoIntro.Add("Atari - Lynx", "Atari - Lynx");
			NoIntro.Add("Atari - ST", "Atari - ST");
			NoIntro.Add("Bandai - WonderSwan", "Bandai - WonderSwan");
			NoIntro.Add("Bandai - WonderSwan Color", "Bandai - WonderSwan Color");
			NoIntro.Add("Casio - Loopy", "Casio - Loopy");
			NoIntro.Add("Casio - PV-1000", "Casio - PV-1000");
			NoIntro.Add("Coleco - ColecoVision", "Coleco - ColecoVision, ColecoVision ADAM");
			NoIntro.Add("Commodore - 64", "Commodore - 64");
			NoIntro.Add("Commodore - 64 (PP)", "Commodore - 64");
			NoIntro.Add("Commodore - 64 (Tapes)", "Commodore - 64");
			NoIntro.Add("Commodore - Amiga", "Commodore - Amiga");
			NoIntro.Add("Commodore - Plus-4", "Commodore - Plus-4");
			NoIntro.Add("Commodore - VIC-20", "Commodore - VIC-20");
			NoIntro.Add("Emerson - Arcadia 2001", "Emerson - Arcadia 2001");
			NoIntro.Add("Entex - Adventure Vision", "Entex - Adventure Vision");
			NoIntro.Add("Epoch - Super Cassette Vision", "Epoch - Super Cassette Vision");
			NoIntro.Add("Fairchild - Channel F", "Fairchild - Channel F");
			NoIntro.Add("Funtech - Super Acan", "Funtech - Super Acan");
			NoIntro.Add("GamePark - GP32", "GamePark - GP32");
			NoIntro.Add("GCE - Vectrex", "GCE - Vectrex");
			NoIntro.Add("Hartung - Game Master", "Hartung - Game Master");
			NoIntro.Add("LeapFrog - Leapster Learning Game System", "LeapFrog - Leapster Learning Game System");
			NoIntro.Add("Magnavox - Odyssey2", "Philips - Videopac+, Odyssey2");
			NoIntro.Add("Microsoft - MSX", "Microsoft - MSX, MSX 2");
			NoIntro.Add("Microsoft - MSX 2", "Microsoft - MSX, MSX 2");
			NoIntro.Add("Microsoft - XBOX 360 (DLC)", "Microsoft - Xbox 360");
			NoIntro.Add("Microsoft - XBOX 360 (Games on Demand)", "Microsoft - Xbox 360");
			NoIntro.Add("Microsoft - XBOX 360 (Title Updates)", "Microsoft - Xbox 360");
			NoIntro.Add("NEC - PC Engine - TurboGrafx 16", "NEC - PC Engine, TurboGrafx 16");
			NoIntro.Add("NEC - Super Grafx", "NEC - Super Grafx");
			NoIntro.Add("Nintendo - Famicom Disk System", "Nintendo - Famicom Disk System");
			NoIntro.Add("Nintendo - Game Boy", "Nintendo - Game Boy");
			NoIntro.Add("Nintendo - Game Boy Advance", "Nintendo - Game Boy Advance");
			NoIntro.Add("Nintendo - Game Boy Advance (e-Cards)", "Nintendo - Game Boy Advance");
			NoIntro.Add("Nintendo - Game Boy Color", "Nintendo - Game Boy Color");
			NoIntro.Add("Nintendo - New Nintendo 3DS", "Nintendo - Nintendo 3DS");
			NoIntro.Add("Nintendo - New Nintendo 3DS (DLC)", "Nintendo - Nintendo 3DS");
			NoIntro.Add("Nintendo - Nintendo 3DS", "Nintendo - Nintendo 3DS");
			NoIntro.Add("Nintendo - Nintendo 3DS (DLC)", "Nintendo - Nintendo 3DS");
			NoIntro.Add("Nintendo - Nintendo 64", "Nintendo - Nintendo 64");
			NoIntro.Add("Nintendo - Nintendo 64DD", "Nintendo - Nintendo 64DD");
			NoIntro.Add("Nintendo - Nintendo DS", "Nintendo - Nintendo DS");
			NoIntro.Add("Nintendo - Nintendo DS (Download Play) (BETA)", "Nintendo - Nintendo DS");
			NoIntro.Add("Nintendo - Nintendo DSi", "Nintendo - Nintendo DSi");
			NoIntro.Add("Nintendo - Nintendo DSi (DLC)", "Nintendo - Nintendo DSi");
			NoIntro.Add("Nintendo - Nintendo Entertainment System", "Nintendo - Nintendo Entertainment System");
			NoIntro.Add("Nintendo - Nintendo Wii (DLC)", "Nintendo - Nintendo Wii");
			NoIntro.Add("Nintendo - Pokemon Mini", "Nintendo - Pokemon Mini");
			NoIntro.Add("Nintendo - Satellaview", "Nintendo - Super Nintendo Entertainment System");
			NoIntro.Add("Nintendo - Sufami Turbo", "Nintendo - Super Nintendo Entertainment System");
			NoIntro.Add("Nintendo - Super Nintendo Entertainment System", "Nintendo - Super Nintendo Entertainment System");
			NoIntro.Add("Nintendo - Virtual Boy", "Nintendo - Virtual Boy");
			NoIntro.Add("Nokia - N-Gage", "Nokia - N-Gage");
			NoIntro.Add("Philips - Videopac+", "Philips - Videopac+, Odyssey2");
			NoIntro.Add("RCA - Studio II", "RCA - Studio II");
			NoIntro.Add("Sega - 32X", "Sega - 32X");
			NoIntro.Add("Sega - Game Gear", "Sega - Game Gear");
			NoIntro.Add("Sega - Master System - Mark III", "Sega - Master System, Mark III");
			NoIntro.Add("Sega - Mega Drive - Genesis", "Sega - Mega Drive, Genesis");
			NoIntro.Add("Sega - PICO", "Sega - PICO");
			NoIntro.Add("Sega - SG-1000", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			NoIntro.Add("Sinclair - ZX Spectrum +3", "Sinclair - ZX Spectrum");
			NoIntro.Add("Sony - PlayStation 3 (DLC)", "Sony - PlayStation 3");
			NoIntro.Add("Sony - PlayStation 3 (Downloadable)", "Sony - PlayStation 3");
			NoIntro.Add("Sony - PlayStation 3 (PSN)", "Sony - PlayStation 3");
			NoIntro.Add("Sony - PlayStation Portable", "Sony - PlayStation Portable");
			NoIntro.Add("Sony - PlayStation Portable (DLC)", "Sony - PlayStation Portable");
			NoIntro.Add("Sony - PlayStation Portable (PSN)", "Sony - PlayStation Portable");
			NoIntro.Add("Sony - PlayStation Portable (PSX2PSP)", "Sony - PlayStation Portable");
			NoIntro.Add("Sony - PlayStation Portable (UMD Music)", "Sony - PlayStation Portable");
			NoIntro.Add("Sony - PlayStation Portable (UMD Video)", "Sony - PlayStation Portable");
			NoIntro.Add("SNK - Neo Geo Pocket", "SNK - Neo Geo Pocket");
			NoIntro.Add("SNK - Neo Geo Pocket Color", "SNK - Neo Geo Pocket Color");
			NoIntro.Add("Tiger - Game.com", "Tiger - Game.com");
			NoIntro.Add("Tiger - Gizmondo", "Tiger - Gizmondo");
			NoIntro.Add("VTech - CreatiVision", "VTech - CreatiVision");
			NoIntro.Add("VTech - V.Smile", "VTech - V.Smile, V.Disc");
			NoIntro.Add("Watara - Supervision", "Watara - Supervision");

			Redump = new Dictionary<string, string>();

			Redump.Add("Apple - Machintosh", "Apple - Macintosh");
			Redump.Add("Arcade - Namco - Sega - Nintendo - Triforce", "Namco - Triforce");
			Redump.Add("Arcade - Sega - Chihiro", "Sega - Chihiro");
			Redump.Add("Arcade - Sega - Lindbergh", "Sega - Lindbergh");
			Redump.Add("Arcade - Sega - Naomi", "Sega - Naomi, Naomi 2, Atomiswave");
			Redump.Add("Bandai - Apple - Pippin", "Bandai - Pippin");
			Redump.Add("Bandai - Playdia", "Bandai - Playdia");
			Redump.Add("Commodore - Amiga CD", "Commodore - Amiga");
			Redump.Add("Commodore - Amiga CD32", "Commodore - Amiga");
			Redump.Add("Commodore - Amiga CDTV", "Commodore - Amiga");
			Redump.Add("Fujitsu - FM-Towns", "Fujitsu - FM Towns");
			Redump.Add("IBM - PC compatible", "IBM - PC Compatibles");
			Redump.Add("Mattel - HyperScan", "Mattel - HyperScan");
			Redump.Add("Microsoft - Xbox - BIOS Images", "Microsoft - Xbox");
			Redump.Add("Microsoft - Xbox", "Microsoft - Xbox");
			Redump.Add("Microsoft - Xbox 360", "Microsoft - Xbox 360");
			Redump.Add("Microsoft - Xbox One", "Microsoft - Xbox One");
			Redump.Add("NEC - PC Engine CD - TurboGrafx-CD", "NEC - PC Engine CD, TurboGrafx 16 CD");
			Redump.Add("NEC - PC-88 series", "NEC - PC-8801");
			Redump.Add("NEC - PC-98 series", "NEC - PC-9801");
			Redump.Add("NEC - PC-FX - PC-FXGA", "NEC - PC FX, PC FXGA");
			Redump.Add("Nintendo - GameCube - BIOS Images", "Nintendo - GameCube");
			Redump.Add("Nintendo - GameCube", "Nintendo - GameCube");
			Redump.Add("Nintendo - Wii", "Nintendo - Wii");
			Redump.Add("Nintendo - Wii U", "Nintendo - Wii U");
			Redump.Add("Palm", "Hewlett-Packard - Palm");
			Redump.Add("Panasonic - 3DO Interactive Multiplayer", "Panasonic - 3DO Interactive Multiplayer");
			Redump.Add("Philips - CD-i", "Philips - CD-i");
			Redump.Add("Sega - Dreamcast", "Sega - Dreamcast");
			Redump.Add("Sega - Mega-CD - Sega CD", "Sega - Mega-CD, Sega CD");
			Redump.Add("Sega - Saturn", "Sega - Saturn");
			Redump.Add("SNK - Neo Geo CD", "SNK - Neo Geo CD");
			Redump.Add("Sony - PlayStation - BIOS Images", "Sony - PlayStation");
			Redump.Add("Sony - PlayStation", "Sony - PlayStation");
			Redump.Add("Sony - PlayStation 2 - BIOS Images", "Sony - PlayStation 2");
			Redump.Add("Sony - PlayStation 2", "Sony - PlayStation 2");
			Redump.Add("Sony - PlayStation 3", "Sony - PlayStation 3");
			Redump.Add("Sony - PlayStation 4", "Sony - PlayStation 4");
			Redump.Add("Sony - PlayStation Portable", "Sony - PlayStation Portable");
			Redump.Add("VTech - V.Flash", "VTech - V.Flash Home Edutainment System");

			TOSEC = new Dictionary<string, string>();

			TOSEC.Add("3DO 3DO Interactive Multiplayer", "Panasonic - 3DO Interactive Multiplayer");
			TOSEC.Add("Acorn Archimedes", "Acorn - Archimedes");
			TOSEC.Add("Acorn BBC", "Acorn BBC, Electron");
			TOSEC.Add("Acorn Electron", "Acorn BBC, Electron");
			TOSEC.Add("Altos Computer Systems ACS-186, 586 & 986", "Altos Computer Systems - ACS-186, 586, 986");
			TOSEC.Add("Altos Computer Systems Series 5", "Altos Computer Systems - ACS Series 5");
			TOSEC.Add("Amstrad CPC", "Amstrad - CPC");
			TOSEC.Add("Amstrad PCW", "Amstrad - PCW");
			TOSEC.Add("APF Imagination Machine", "APF - M-1000");
			TOSEC.Add("American Laser Games CD-ROM System", "American Laser Games - CD-ROM System");
			TOSEC.Add("Apple 1", "Apple - I");
			TOSEC.Add("Apple II", "Apple - II");
			TOSEC.Add("Apple IIGS", "Apple - II");
			TOSEC.Add("Apple III", "Apple - III");
			TOSEC.Add("Apple Macintosh", "Apple - Macintosh");
			TOSEC.Add("Apple Lisa", "Apple - Lisa");
			TOSEC.Add("Applied Technology MicroBee", "Applied Technology - MicroBee");
			TOSEC.Add("Atari 8bit", "Atari - 8bit");
			TOSEC.Add("Atari 2600 & VCS", "Atari - 2600");
			TOSEC.Add("Atari 5200", "Atari - 5200");
			TOSEC.Add("Atari 7800", "Atari - 7200");
			TOSEC.Add("Atari Jaguar", "Atari - Jaguar");
			TOSEC.Add("Atari Jaguar CD", "Atari - Jaguar CD");
			TOSEC.Add("Atari Lynx", "Atari - Lynx");
			TOSEC.Add("Atari ST", "Atari - ST");
			TOSEC.Add("Bally Professional Arcade & Astrocade", "Bally Professional - Arcade, Astrocade");
			TOSEC.Add("Bandai Pippin @World & Pippin Atmark", "Bandai - Pippin");
			TOSEC.Add("Bandai Playdia", "Bandai - Playdia");
			TOSEC.Add("Bandai WonderSwan", "Bandai - WonderSwan");
			TOSEC.Add("Bandai WonderSwan Color", "Bandai - WonderSwan Color");
			TOSEC.Add("Bondwell 2", "Bondwell - 2");
			TOSEC.Add("Bondwell 12", "Bondwell - 12");
			TOSEC.Add("Camputers Lynx", "Camputers - Lynx");
			TOSEC.Add("Capcom CP System III", "Capcom - CPS III");
			TOSEC.Add("Casio CFX-9850", "Casio - CFX-9850");
			TOSEC.Add("Casio Loopy", "Casio - Loopy");
			TOSEC.Add("Casio PB-1000", "Casio - PB-1000");
			TOSEC.Add("Casio PV-2000", "Casio - PV-2000");
			TOSEC.Add("Coleco ColecoVision", "Coleco - ColecoVision, ColecoVision ADAM");
			TOSEC.Add("Coleco ColecoVision ADAM", "Coleco - ColecoVision, ColecoVision ADAM");
			TOSEC.Add("Commodore Amiga", "Commodore - Amiga");
			TOSEC.Add("Commodore Amiga CD32", "Commodore - Amiga");
			TOSEC.Add("Commodore Amiga CDTV", "Commodore - Amiga");
			TOSEC.Add("Commodore C16, C116 & Plus-4", "Commodore - Plus-4");
			TOSEC.Add("Commodore C64", "Commodore - 64");
			TOSEC.Add("Commodore C64DTV", "Commodore - 64 DTV");
			TOSEC.Add("Commodore C65", "Commodore - 65");
			TOSEC.Add("Commodore C128", "Commodore - 128");
			TOSEC.Add("Commodore MAX Machine & VIC10", "Commodore - VIC-10");
			TOSEC.Add("Commodore PET", "Commodore - PET");
			TOSEC.Add("Commodore VIC20", "Commodore - VIC-20");
			TOSEC.Add("Creatronic Mega Duck & Cougar Boy", "Creatronic - Mega Duck, Cougar Boy");
			TOSEC.Add("Cybiko Cybiko", "Cybiko - Cybiko");
			TOSEC.Add("Cybiko Xtreme", "Cybiko - Xtreme");
			TOSEC.Add("DEC PDP-1", "DEC - PDP-1");
			TOSEC.Add("DEC PDP-7", "DEC - PDP-7");
			TOSEC.Add("DEC PDP-8", "DEC - PDP-8");
			TOSEC.Add("DEC PDP-9", "DEC - PDP-9");
			TOSEC.Add("DEC PDP-10", "DEC - PDP-10");
			TOSEC.Add("DEC PDP-11", "DEC - PDP-11");
			TOSEC.Add("DEC PDP-12", "DEC - PDP-12");
			TOSEC.Add("DEC PDP-15", "DEC - PDP-15");
			TOSEC.Add("Dragon Data Dragon", "Dragon Data - Dragon");
			TOSEC.Add("EACA EG2000 Colour Genie", "EACA - EG2000 Colour Genie");
			TOSEC.Add("Elektronika BK-0010-0011M", "Elektronika BK-0010");
			TOSEC.Add("Elektronika BK-0011-411", "Elektronika BK-0010");
			TOSEC.Add("Elektronska Industrija Nis PECOM 32 & 64", "Elektronska Industrija Nis - PECOM 32, 64");
			TOSEC.Add("Emerson Arcadia 2001", "Emerson - Arcadia 2001");
			TOSEC.Add("Enterprise 64 & 128", "Enterprise - 64, 128");
			TOSEC.Add("Entex Adventure Vision", "Entex - Adventure Vision");
			TOSEC.Add("Epoch Super Cassette Vision", "Epoch - Super Cassette Vision");
			TOSEC.Add("Epson PX-8, HC-88 & Geneva", "Epson - PX-8, HC-88, Geneva");
			TOSEC.Add("ETL Mark II", "ETL - Mark II");
			TOSEC.Add("ETL Mark IV", "ETL - Mark IV");
			TOSEC.Add("ETL Mark IV A", "ETL - Mark IV A");
			TOSEC.Add("Exelvision Exeltel", "Exelvision - Exeltel, EXL100");
			TOSEC.Add("Exelvision EXL100", "Exelvision - Exeltel, EXL100");
			TOSEC.Add("Exidy Sorcerer", "Exidy - Sorcerer");
			TOSEC.Add("Fairchild VES & Channel F", "Fairchild - Channel F");
			TOSEC.Add("Front Fareast Magic Drive", "Front Fareast - Magic Drive");
			TOSEC.Add("Fuji Photo Film FUJIC", "Fuji Photo Film - FUJIC");
			TOSEC.Add("Fujitsu FM Towns", "Fujitsu - FM Towns");
			TOSEC.Add("Fujitsu FM-7", "Fujitsu - FM-7");
			TOSEC.Add("Funtech Super Acan", "Funtech - Super Acan");
			TOSEC.Add("Galaksija Galaksija", "Galaksija - Galaksija, Galaksija Plus");
			TOSEC.Add("Galaksija Galaksija Plus", "Galaksija - Galaksija, Galaksija Plus");
			TOSEC.Add("Game Park GP32", "GamePark - GP32");
			TOSEC.Add("GCE Vectrex", "GCE - Vectrex");
			TOSEC.Add("Hewlett-Packard HP48", "Hewlett-Packard - HP48");
			TOSEC.Add("Hewlett-Packard HP49", "Hewlett-Packard - HP49");
			TOSEC.Add("HomeLab BraiLab", "HomeLab - BraiLab");
			TOSEC.Add("HomeLab HomeLab", "HomeLab - HomeLab");
			TOSEC.Add("IBM PC Compatibles", "IBM - PC Compatibles");
			TOSEC.Add("IBM PCjr", "IBM - PC Jr");
			TOSEC.Add("Incredible Technologies Eagle", "Incredible Technologies - Eagle");
			TOSEC.Add("Infocom Z-Machine", "Infocom - Z-Machine");
			TOSEC.Add("Interact Family Computer", "Interact - Family Computer");
			TOSEC.Add("Jupiter Cantab Jupiter Ace", "Jupiter Cantab - Jupiter Ace");
			TOSEC.Add("Kaypro II", "Kaypro - II");
			TOSEC.Add("Keio University K-1", "University of Keio - K-1");
			TOSEC.Add("Konami Bemani System 573 Analog", "Konami - System 573");
			TOSEC.Add("Konami Bemani System 573 Digital", "Konami - System 573");
			TOSEC.Add("Konami System 573", "Konami - System 573");
			TOSEC.Add("Luxor ABC 80", "Luxor - ABC 80");
			TOSEC.Add("Luxor ABC 800", "Luxor - ABC 800");
			TOSEC.Add("Luxor Video Entertainment System", "Luxor - Video Entertainment System");
			TOSEC.Add("Magnavox Odyssey2", "Philips - Videopac+, Odyssey2");
			TOSEC.Add("Matra Hachette Alice 32", "Matra Hachette - Alice 32 & 90");
			TOSEC.Add("Matsushita National JR 200", "Matsushita National - JR 200");
			TOSEC.Add("Mattel Aquarius", "Mattel - Aquarius");
			TOSEC.Add("Mattel HyperScan", "Mattel - HyperScan");
			TOSEC.Add("Mattel Intellivision", "Mattel - Intellivision");
			TOSEC.Add("Memorex Video Information System", "Memorex - Video Information System");
			TOSEC.Add("Memotech MTX", "Memotech MTX512");
			TOSEC.Add("MGT Sam Coupe", "MGT - Sam Coupe");
			TOSEC.Add("Microkey Primo", "Microkey - Primo");
			TOSEC.Add("MITS Altair 8800", "MITS - Altair 8800");
			TOSEC.Add("MSX MSX", "Microsoft - MSX, MSX 2");
			TOSEC.Add("MSX MSX2", "Microsoft - MSX, MSX 2");
			TOSEC.Add("MSX MSX2+", "Microsoft - MSX, MSX 2");
			TOSEC.Add("MSX TurboR", "Microsoft - MSX, MSX 2");
			TOSEC.Add("Nascom I & II", "Nascom - I, II");
			TOSEC.Add("NCR Decision Mate V", "NCR - Decision Mate V");
			TOSEC.Add("NEC PC-88VA", "NEC - PC-88VA");
			TOSEC.Add("NEC PC-6001", "NEC - PC-6001");
			TOSEC.Add("NEC PC-8001", "NEC - PC-8001");
			TOSEC.Add("NEC PC-8201", "NEC - PC-8201");
			TOSEC.Add("NEC PC-8801", "NEC - PC-8801");
			TOSEC.Add("NEC PC-9801", "NEC - PC-9801");
			TOSEC.Add("NEC PC-9821", "NEC - PC-9801");
			TOSEC.Add("NEC PC-Engine & TurboGrafx-16", "NEC - PC Engine, TurboGrafx 16");
			TOSEC.Add("NEC PC-Engine CD & TurboGrafx-16 CD", "NEC - PC Engine CD, TurboGrafx 16 CD");
			TOSEC.Add("NEC PC-FX", "NEC - PC FX, PC FXGA");
			TOSEC.Add("NEC PC-FXGA", "NEC - PC FX, PC FXGA");
			TOSEC.Add("NEC SuperGrafx", "NEC - Super Grafx");
			TOSEC.Add("Nintendo 64", "Nintendo - Nintendo 64");
			TOSEC.Add("Nintendo 64DD", "Nintendo - Nintendo 64DD");
			TOSEC.Add("Nintendo Famicom & Entertainment System", "Nintendo - Nintendo Entertainment System");
			TOSEC.Add("Nintendo Famicom Disk System", "Nintendo - Famicom Disk System");
			TOSEC.Add("Nintendo Game Boy", "Nintendo - Game Boy");
			TOSEC.Add("Nintendo Game Boy Advance", "Nintendo - Game Boy Advance");
			TOSEC.Add("Nintendo Game Boy Color", "Nintendo - Game Boy Color");
			TOSEC.Add("Nintendo GameCube", "Nintendo - GameCube");
			TOSEC.Add("Nintendo Pokemon Mini", "Nintendo - Pokemon Mini");
			TOSEC.Add("Nintendo Super Famicom & Super Entertainment System", "Nintendo - Super Nintendo Entertainment System");
			TOSEC.Add("Nintendo Virtual Boy", "Nintendo - Virtual Boy");
			TOSEC.Add("OCC Osborne 1 & Osborne Executive", "OCC - Osborne 1, 2, 3, 4");
			TOSEC.Add("OpenPandora Pandora", "OpenPandora - Pandora");
			TOSEC.Add("PEL Varazdin Orao", "PEL Varazdin - Orao");
			TOSEC.Add("Philips CD-i", "Philips - CD-i");
			TOSEC.Add("Philips P2000", "Philips - P2000");
			TOSEC.Add("Philips VG 5000", "Philips - VG 5000");
			TOSEC.Add("Philips Videopac+", "Philips - Videopac+, Odyssey2");
			TOSEC.Add("Pioneer LaserActive", "Pioneer - LaserActive");
			TOSEC.Add("PTC Sol Terminal Computer SOL-20", "PTC - Sol Terminal Computer SOL-20");
			TOSEC.Add("Radica Arcade Legends & Play TV Legends", "Radica - Arcade Legends, Play TV Legends");
			TOSEC.Add("Radio-86RK Apogej BK-01", "Radio-86RK - Apogej BK-01");
			TOSEC.Add("Radio-86RK Mikro-80", "Radio-86RK - Mikro-80");
			TOSEC.Add("Radio-86RK Mikrosha", "Radio-86RK - Mikrosha");
			TOSEC.Add("Radio-86RK Partner-01.01", "Radio-86RK - Partner-01.01");
			TOSEC.Add("Radio-86RK Radio-86RK", "Radio-86RK - Radio-86RK");
			TOSEC.Add("Radio-86RK YuT-88", "Radio-86RK - YuT-88");
			TOSEC.Add("RCA Chip-8", "RCA - Chip-8");
			TOSEC.Add("RCA Studio II", "RCA - Studio II");
			TOSEC.Add("RCA Superchip", "RCA - Superchip");
			TOSEC.Add("RM Nimbus PC", "RM - Nimbus PC");
			TOSEC.Add("Robotron HC900, KC85 2, KC85 3 & KC85 4", "Robotron - KC85");
			TOSEC.Add("Robotron KC Compact", "Robotron - KC Compact");
			TOSEC.Add("Robotron Z1013", "Robotron - Z1013");
			TOSEC.Add("Robotron Z9001 & KC85 1", "Robotron - KC85");
			TOSEC.Add("SABA Videoplay", "Fairchild - Channel F");
			TOSEC.Add("Sega 32X", "Sega - 32X");
			TOSEC.Add("Sega Computer 3000", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			TOSEC.Add("Sega Dreamcast", "Sega - Dreamcast");
			TOSEC.Add("Sega Game 1000", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			TOSEC.Add("Sega Game Gear", "Sega - Game Gear");
			TOSEC.Add("Sega Mark III & Master System", "Sega - Master System, Mark III");
			TOSEC.Add("Sega Mega Drive & Genesis", "Sega - Mega Drive, Genesis");
			TOSEC.Add("Sega Mega-CD and Sega CD", "Sega - Mega-CD, Sega CD");
			TOSEC.Add("Sega NAOMI", "Sega - Naomi, Naomi 2, Atomiswave");
			TOSEC.Add("Sega NAOMI 2", "Sega - Naomi, Naomi 2, Atomiswave");
			TOSEC.Add("Sega Pico", "Sega - PICO");
			TOSEC.Add("Sega Saturn", "Sega - Saturn");
			TOSEC.Add("Sega Super Control Station", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			TOSEC.Add("Sega Visual Memory System", "Sega - Visual Memory System");
			TOSEC.Add("Sega WonderMega", "Sega - Mega-CD, Sega CD");
			TOSEC.Add("Sharp MZ-700", "Sharp - MZ-700");
			TOSEC.Add("Sharp MZ-800 & MZ-1500", "Sharp - MZ-800, MZ-1500");
			TOSEC.Add("Sharp X1", "Sharp - X1");
			TOSEC.Add("Sharp X1 Turbo", "Sharp - X1");
			TOSEC.Add("Sharp X68000", "Sharp - X68000");
			TOSEC.Add("Sinclair QL", "Sinclair - QL");
			TOSEC.Add("Sinclair ZX Spectrum", "Sinclair - ZX Spectrum");
			TOSEC.Add("Sinclair ZX81", "Sinclair - ZX81");
			TOSEC.Add("SNK Hyper Neo-Geo 64", "SNK - Hyper Neo Geo 64");
			TOSEC.Add("SNK Neo-Geo CD", "SNK - Neo Geo CD");
			TOSEC.Add("SNK Neo-Geo Pocket", "SNK - Neo Geo Pocket");
			TOSEC.Add("SNK Neo-Geo Pocket Color", "SNK - Neo Geo Pocket Color");
			TOSEC.Add("Sony PlayStation", "Sony - PlayStation");
			TOSEC.Add("Sony PlayStation 2", "Sony - PlayStation 2");
			TOSEC.Add("Sony PocketStation", "Sony - PocketStation");
			TOSEC.Add("Sord M5", "Sord - M5");
			TOSEC.Add("Spectravideo SVI-318 & SVI-328", "Spectravideo - SVI-318, SVI-328");
			TOSEC.Add("Tandy Radio Shack TRS-80 Color Computer", "Tandy Radio Shack - TRS-80 Color Computer");
			TOSEC.Add("Tandy Radio Shack TRS-80 MC-10", "Tandy Radio Shack - TRS-80 MC-10");
			TOSEC.Add("Tandy Radio Shack TRS-80 Model 4", "Tandy Radio Shack - TRS-80 Model 4");
			TOSEC.Add("Tandy Radio Shack TRS-80 Model 100", "Tandy Radio Shack - TRS-80 Model 100");
			TOSEC.Add("Tandy Radio Shack TRS-80 Model I", "Tandy Radio Shack - TRS-80 Model I");
			TOSEC.Add("Tandy Radio Shack TRS-80 Model III", "Tandy Radio Shack - TRS-80 Model III");
			TOSEC.Add("Tangerine Microtan 65", "Tangerine - Microtan 65");
			TOSEC.Add("Tangerine Oric-1 & Oric Atmos", "Tangerine - Oric-1, Oric Atmos");
			TOSEC.Add("Tatung Einstein TC-01", "Tatung - Einstein TC-01");
			TOSEC.Add("Technosys Aamber Pegasus", "Technosys - Aamber Pegasus");
			TOSEC.Add("Tesla PMD 85", "Tesla - PMD 85");
			TOSEC.Add("Texas Instruments CC-40", "Texas Instruments - CC-40");
			TOSEC.Add("Texas Instruments TI-73", "Texas Instruments - TI-73");
			TOSEC.Add("Texas Instruments TI-80", "Texas Instruments - TI-80");
			TOSEC.Add("Texas Instruments TI-81", "Texas Instruments - TI-81");
			TOSEC.Add("Texas Instruments TI-82", "Texas Instruments - TI-82");
			TOSEC.Add("Texas Instruments TI-83", "Texas Instruments - TI-83");
			TOSEC.Add("Texas Instruments TI-85", "Texas Instruments - TI-85");
			TOSEC.Add("Texas Instruments TI-86", "Texas Instruments - TI-86");
			TOSEC.Add("Texas Instruments TI-89", "Texas Instruments - TI-89");
			TOSEC.Add("Texas Instruments TI-92", "Texas Instruments - TI-92");
			TOSEC.Add("Texas Instruments TI-99 4A", "Texas Instruments - TI-99 4A");
			TOSEC.Add("Thomson MO5", "Thomson - 8bit");
			TOSEC.Add("Thomson MO6", "Thomson - 8bit");
			TOSEC.Add("Thomson TO7", "Thomson - 8bit");
			TOSEC.Add("Thomson TO8", "Thomson - 8bit");
			TOSEC.Add("Thomson TO9+", "Thomson - 8bit");
			TOSEC.Add("Tiger Game.com", "Tiger - Game.com");
			TOSEC.Add("Tiki Data Kontiki-100 & Tiki-100", "Tiki Data - Kontiki-100, Tiki-100");
			TOSEC.Add("Tomy KISS-Site", "Tomy - Kiss-site");
			TOSEC.Add("Tomy Tutor & Pyuuta", "Tomy - Tutor, Pyuuta");
			TOSEC.Add("Tsukuda Original Othello Multivision", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			TOSEC.Add("University of Cambridge EDSAC", "University of Cambridge - EDSAC");
			TOSEC.Add("University of Tokyo PC-1", "University of Tokyo - PC-1");
			TOSEC.Add("Videoton TV-Computer", "Videoton - TV-Computer");
			TOSEC.Add("Visual Technology Visual 1050", "Visual Technology - Visual 1050");
			TOSEC.Add("VM Labs Nuon", "VM Labs - Nuon");
			TOSEC.Add("VTech V.Flash Home Edutainment System", "VTech - V.Flash Home Edutainment System");
			TOSEC.Add("VTech Laser 200", "VTech - Laser");
			TOSEC.Add("VTech Laser 310", "VTech - Laser");
			TOSEC.Add("VTech Laser 2001 & CreatiVision", "VTech - CreatiVision");
			TOSEC.Add("Wang VS", "Wang - VS");
			TOSEC.Add("Watara Supervision", "Watara - SuperVision");
			TOSEC.Add("ZAPiT Games Game Wave Family Entertainment System", "ZAPiT Games - Game Wave Family Entertainment System");

			TruRip = new Dictionary<string, string>();

			TruRip.Add("Acorn Archimedes", "Acorn - Archimedes");
			TruRip.Add("Acorn Archimedes CD", "Acorn - Archimedes");
			TruRip.Add("Acorn BBC Microcomputer System", "Acorn - BBC, Electron");
			TruRip.Add("American Laser Games American Laser Games (Arcade)", "American Laser Games - CD-ROM System");
			TruRip.Add("Amstrad GX4000", "Amstrad - GX4000");
			TruRip.Add("Andamiro Pump It Up (Arcade)", "Andamiro - Pump It Up");
			TruRip.Add("Apple Macintosh CD", "Apple - Macintosh");
			TruRip.Add("Atari 5200", "Atari - 5200");
			TruRip.Add("Atari 7800", "Atari - 7800");
			TruRip.Add("Atari Jaguar CD", "Atari - Jaguar CD");
			TruRip.Add("Atari Lynx", "Atari - Lynx");
			TruRip.Add("Bandai Pippin @World & Atmark", "Bandai Pippin");
			TruRip.Add("Bandai Playdia", "Bandai - Playdia");
			TruRip.Add("Bandai WonderSwan Color (SwanCrystal)", "Bandai - WonderSwan Color");
			TruRip.Add("Bandai WonderSwan", "Bandai - WonderSwan");
			TruRip.Add("Capcom CP SYSTEM III", "Capcom - CPS III");
			TruRip.Add("Commodore Amiga CD", "Commodore - Amiga");
			TruRip.Add("Commodore Amiga CD32", "Commodore - Amiga");
			TruRip.Add("Commodore Amiga CDTV", "Commodore - Amiga");
			TruRip.Add("Fairchild Channel F (Video Entertainment System)", "Fairchild - Channel F");
			TruRip.Add("Fujitsu FM Towns (Marty)", "Fujitsu - FM Towns");
			TruRip.Add("IBM PC Compatible IBM PC compatible", "IBM - PC Compatibles");
			TruRip.Add("Incredible Technologies IT Eagle", "Incredible Technologies - Eagle");
			TruRip.Add("Incredible Technologies IT PC", "Incredible Technologies - PC");
			TruRip.Add("Konami Bemani FireBeat", "Konami - Bemani FireBeat");
			TruRip.Add("Konami Bemani Twinkle", "Konami - Bemani Twinkle");
			TruRip.Add("Konami M2", "Panasonic - 3DO M2");
			TruRip.Add("Konami System 573", "Konami - System 573");
			TruRip.Add("Mattel HyperScan", "Mattel - HyperScan");
			TruRip.Add("Memorex VIS interactive Video Information", "Memorex - Video Information System");
			TruRip.Add("MSX MSX CD", "Microsoft - MSX, MSX 2");
			TruRip.Add("Namco - Sega - Nintendo Triforce", "Namco - Triforce");
			TruRip.Add("Namco System 2x6", "Namco - System 246, System 256");
			TruRip.Add("NCR Decision Mate V", "NCR - Decision Mate V");
			TruRip.Add("NEC PC Engine CD & TurboGrafx CD", "NEC - PC Engine CD, TurboGrafx 16 CD");
			TruRip.Add("NEC PC-FX", "NEC - PC FX, PC FXGA");
			TruRip.Add("NEC PC-FXGA", "NEC - PC FX, PC FXGA");
			TruRip.Add("Panasonic 3DO Interactive Multiplayer", "Panasonic - 3DO Interactive Multiplayer");
			TruRip.Add("Philips CD-i & VCD", "Philips - CD-i");
			TruRip.Add("Philips Videopac + G7400", "Philips - Videopac+, Odyssey2");
			TruRip.Add("Sega Chihiro", "Sega - Chihiro");
			TruRip.Add("Sega Dreamcast", "Sega - Dreamcast");
			TruRip.Add("Sega Lindbergh", "Sega - Lindbergh");
			TruRip.Add("Sega Mega-CD & Sega CD", "Sega - Mega-CD, Sega CD");
			TruRip.Add("Sega NAOMI 2", "Sega - Naomi, Naomi 2, Atomiswave");
			TruRip.Add("Sega NAOMI", "Sega - Naomi, Naomi 2, Atomiswave");
			TruRip.Add("Sega RingWide", "Sega - RingWide");
			TruRip.Add("Sega Saturn", "Sega - Saturn");
			TruRip.Add("Sharp X1", "Sharp - X1");
			TruRip.Add("SNK Neo-Geo CD", "SNK - Neo Geo CD");
			TruRip.Add("Sony PlayStation & PSone", "Sony - PlayStation");
			TruRip.Add("Sord CGL M 5 (M 5, Game M 5)", "Sord - M5");
			TruRip.Add("Spectravideo SV-318 & SV-328", "Spectravideo - SVI-318, SVI-328");
			TruRip.Add("Tesla PMD-85", "Tesla - PMD 85");
			TruRip.Add("Tiger Game.com", "Tiger - Game.com");
			TruRip.Add("Tomy Grandstand Tutor (Tutor, Pyuuta)", "Tomy - Tutor, Pyuuta");
			TruRip.Add("Tomy Kiss-site", "Tomy - Kiss-site");
			TruRip.Add("Tsukuda Original Othello Multivision", "Sega - SG-1000, SC-3000, SF-7000, Othello Multivision");
			TruRip.Add("Vidoton TV-Computer", "Videoton - TV-Computer");
			TruRip.Add("VM Labs Nuon", "VM Labs - Nuon");
			TruRip.Add("VTech V.Flash Home Edutainment System", "VTech - V.Flash Home Edutainment System");
			TruRip.Add("Wang VS", "Wang - VS");
			TruRip.Add("Watara SuperVision (Quickshot, Hartung SV-100, HiperVision, Tiger Boy)", "Watara - Supervision");
			TruRip.Add("ZAPiT Games Game Wave Family Entertainment System", "ZAPiT Games - Game Wave Family Entertainment System");
        }
	}
}
